### ISSUE TITLE
`reqwest` problem: blocking client fails in async context

### ISSUE THREAD

**Issue by sergey-melnychuk** [eigerco/beerus#626]
It turns out that blocking `reqwest::Client` is extremely unfriendly to the asynchronous contexts: [the likely root cause](https://github.com/seanmonstar/reqwest/issues/1233). At this point this problem is a blocker for stateless execution, as blocking client is used to pull actual state from the RPC provider.

```
$ RUST_BACKTRACE=1 RUST_LOG=info cargo test --package beerus-experimental-api --test rpc -- test_call
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running tests/rpc.rs (target/debug/deps/rpc-abec836374fdeb4b)

running 1 test
test test_call ... FAILED

failures:

---- test_call stdout ----
thread 'test_call' panicked at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/shutdown.rs:51:21
   3: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:261:12
   4: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:278:9
   5: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ptr/mod.rs:507:1
   6: core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ptr/mod.rs:507:1
   7: reqwest::blocking::wait::enter
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/wait.rs:76:21
   8: reqwest::blocking::wait::timeout
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/wait.rs:13:5
   9: reqwest::blocking::client::ClientHandle::new
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/client.rs:1075:15
  10: reqwest::blocking::client::ClientBuilder::build
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/client.rs:103:9
  11: reqwest::blocking::client::Client::new
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/client.rs:877:9
  12: beerus_experimental_api::gen::gen::client::blocking::Client::new
             at ./src/gen.rs:7467:33
  13: <beerus_experimental_api::rpc::Context as beerus_experimental_api::gen::gen::Rpc>::call::{{closure}}
             at ./src/rpc.rs:178:22
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
  15: beerus_experimental_api::gen::gen::handle_call::{{closure}}
             at ./src/gen.rs:2720:43
  16: beerus_experimental_api::gen::gen::handle::{{closure}}
             at ./src/gen.rs:3652:57
  17: beerus_experimental_api::rpc::handle_request::{{closure}}
             at ./src/rpc.rs:114:47
  18: <F as axum::handler::Handler<(M,T1,T2),S>>::call::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/handler/mod.rs:241:53
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  21: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  22: <axum::handler::future::IntoServiceFuture<F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/macros.rs:42:17
  23: <F as futures_core::future::TryFuture>::try_poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/future.rs:82:9
  24: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/try_future/into_future.rs:34:9
  25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  26: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  27: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  28: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/macros.rs:38:17
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
  30: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/util/oneshot.rs:97:38
  31: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/routing/route.rs:162:61
  32: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/util/oneshot.rs:97:38
  33: <axum::serve::TowerToHyperServiceFuture<S,R> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/serve.rs:480:9
  34: <hyper::proto::h1::dispatch::Server<S,hyper::body::incoming::Incoming> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:514:35
  35: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:312:43
  36: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:171:21
  37: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:147:16
  38: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:126:28
  39: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/proto/h1/dispatch.rs:447:9
  40: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.2.0/src/server/conn/http1.rs:498:22
  41: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.3/src/server/conn/auto.rs:475:28
  42: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/future/future.rs:124:9
  43: <axum::serve::WithGracefulShutdown<M,S,F> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/macros/select.rs:524:49
  44: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/future/poll_fn.rs:58:9
  45: <axum::serve::WithGracefulShutdown<M,S,F> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/serve.rs:346:25
  46: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:328:17
  47: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/loom/std/unsafe_cell.rs:16:9
  48: tokio::runtime::task::core::Core<T,S>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:317:13
  49: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:485:19
  50: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  51: std::panicking::try::do_call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  52: __rust_try
  53: std::panicking::try
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  54: std::panic::catch_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  55: tokio::runtime::task::harness::poll_future
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:473:18
  56: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:208:27
  57: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:153:15
  58: tokio::runtime::task::raw::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:271:5
  59: tokio::runtime::task::raw::RawTask::poll
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:201:18
  60: tokio::runtime::task::LocalNotified<S>::run
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/mod.rs:416:9
  61: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:700:25
  62: tokio::runtime::coop::with_budget
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  63: tokio::runtime::coop::budget
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  64: tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:343:43
  65: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  66: tokio::runtime::scheduler::current_thread::Context::run_task
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:343:23
  67: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:699:35
  68: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  69: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/scoped.rs:40:9
  70: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:26
  71: std::thread::local::LocalKey<T>::try_with
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:286:16
  72: std::thread::local::LocalKey<T>::with
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/local.rs:262:9
  73: tokio::runtime::context::set_scheduler
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:9
  74: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  75: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  76: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  77: tokio::runtime::context::runtime::enter_runtime
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  78: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  79: tokio::runtime::runtime::Runtime::block_on
             at /home/work/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/runtime.rs:348:47
  80: rpc::test_call
             at ./tests/rpc.rs:106:5
  81: rpc::test_call::{{closure}}
             at ./tests/rpc.rs:85:25
  82: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  83: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Rpc(Error { code: 4002, message: "Request failed: error sending request for url (http://localhost:40289/rpc): connection closed before message completed." })


failures:
    test_call

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 19 filtered out; finished in 0.17s
```

**Comment by sergey-melnychuk** [comment]
Fixed in https://github.com/vishnubob/wait-for-it/tree/master
